// Code generated by gowinmd; DO NOT EDIT.

package bcrypt

// Types used in generated APIs for

type PKCS1_PADDING_INFO struct {
	PszAlgId *PWSTRElement
}

type PSS_PADDING_INFO struct {
	PszAlgId *PWSTRElement
	CbSalt   uint32
}

type OAEP_PADDING_INFO struct {
	PszAlgId *PWSTRElement
	PbLabel  *uint8
	CbLabel  uint32
}

type PQDSA_PADDING_INFO struct {
	PbCtx           *uint8
	CbCtx           uint32
	PszPrehashAlgId *PWSTRElement
}

type AUTHENTICATED_CIPHER_MODE_INFO struct {
	CbSize        uint32
	DwInfoVersion uint32
	PbNonce       *uint8
	CbNonce       uint32
	PbAuthData    *uint8
	CbAuthData    uint32
	PbTag         *uint8
	CbTag         uint32
	PbMacContext  *uint8
	CbMacContext  uint32
	CbAAD         uint32
	_             [4]byte
	CbData        uint64
	DwFlags       uint32
	_             [4]byte
}

type PWSTRElement uint16
