// Code generated by gowinmd; DO NOT EDIT.

package bcrypt

import "unsafe"

var _ unsafe.Pointer

// APIs for Windows.Win32.Security.Cryptography
//sys	OpenAlgorithmProvider(phAlgorithm *BCRYPT_ALG_HANDLE, pszAlgId *uint16, pszImplementation *uint16, dwFlags BCRYPT_OPEN_ALGORITHM_PROVIDER_FLAGS) (ntstatus error) = bcrypt.BCryptOpenAlgorithmProvider
//sys	GetProperty(hObject BCRYPT_HANDLE, pszProperty *uint16, pbOutput []byte, pcbResult *uint32, dwFlags uint32) (ntstatus error) = bcrypt.BCryptGetProperty
//sys	SetProperty(hObject BCRYPT_HANDLE, pszProperty *uint16, pbInput []byte, dwFlags uint32) (ntstatus error) = bcrypt.BCryptSetProperty
//sys	CloseAlgorithmProvider(hAlgorithm BCRYPT_ALG_HANDLE, dwFlags uint32) (ntstatus error) = bcrypt.BCryptCloseAlgorithmProvider
//sys	GenerateKeyPair(hAlgorithm BCRYPT_ALG_HANDLE, phKey *BCRYPT_KEY_HANDLE, dwLength uint32, dwFlags uint32) (ntstatus error) = bcrypt.BCryptGenerateKeyPair
//sys	ExportKey(hKey BCRYPT_KEY_HANDLE, hExportKey BCRYPT_KEY_HANDLE, pszBlobType *uint16, pbOutput []byte, pcbResult *uint32, dwFlags uint32) (ntstatus error) = bcrypt.BCryptExportKey
//sys	ImportKeyPair(hAlgorithm BCRYPT_ALG_HANDLE, hImportKey BCRYPT_KEY_HANDLE, pszBlobType *uint16, phKey *BCRYPT_KEY_HANDLE, pbInput []byte, dwFlags uint32) (ntstatus error) = bcrypt.BCryptImportKeyPair
//sys	FinalizeKeyPair(hKey BCRYPT_KEY_HANDLE, dwFlags uint32) (ntstatus error) = bcrypt.BCryptFinalizeKeyPair
//sys	DestroyKey(hKey BCRYPT_KEY_HANDLE) (ntstatus error) = bcrypt.BCryptDestroyKey
//sys	DestroySecret(hSecret BCRYPT_SECRET_HANDLE) (ntstatus error) = bcrypt.BCryptDestroySecret
//sys	SignHash(hKey BCRYPT_KEY_HANDLE, pPaddingInfo unsafe.Pointer, pbInput []byte, pbOutput []byte, pcbResult *uint32, dwFlags BCRYPT_FLAGS) (ntstatus error) = bcrypt.BCryptSignHash
//sys	VerifySignature(hKey BCRYPT_KEY_HANDLE, pPaddingInfo unsafe.Pointer, pbHash []byte, pbSignature []byte, dwFlags BCRYPT_FLAGS) (ntstatus error) = bcrypt.BCryptVerifySignature
//sys	SecretAgreement(hPrivKey BCRYPT_KEY_HANDLE, hPubKey BCRYPT_KEY_HANDLE, phAgreedSecret *BCRYPT_SECRET_HANDLE, dwFlags uint32) (ntstatus error) = bcrypt.BCryptSecretAgreement
//sys	DeriveKey(hSharedSecret BCRYPT_SECRET_HANDLE, pwszKDF *uint16, pParameterList *BCryptBufferDesc, pbDerivedKey []byte, pcbResult *uint32, dwFlags uint32) (ntstatus error) = bcrypt.BCryptDeriveKey
//sys	KeyDerivation(hKey BCRYPT_KEY_HANDLE, pParameterList *BCryptBufferDesc, pbDerivedKey []byte, pcbResult *uint32, dwFlags uint32) (ntstatus error) = bcrypt.BCryptKeyDerivation
//sys	CreateHash(hAlgorithm BCRYPT_ALG_HANDLE, phHash *BCRYPT_HASH_HANDLE, pbHashObject []byte, pbSecret []byte, dwFlags uint32) (ntstatus error) = bcrypt.BCryptCreateHash
//sys	HashData(hHash BCRYPT_HASH_HANDLE, pbInput []byte, dwFlags uint32) (ntstatus error) = bcrypt.BCryptHashData
//sys	FinishHash(hHash BCRYPT_HASH_HANDLE, pbOutput []byte, dwFlags uint32) (ntstatus error) = bcrypt.BCryptFinishHash
//sys	DuplicateHash(hHash BCRYPT_HASH_HANDLE, phNewHash *BCRYPT_HASH_HANDLE, pbHashObject []byte, dwFlags uint32) (ntstatus error) = bcrypt.BCryptDuplicateHash
//sys	DestroyHash(hHash BCRYPT_HASH_HANDLE) (ntstatus error) = bcrypt.BCryptDestroyHash
//sys	Hash(hAlgorithm BCRYPT_ALG_HANDLE, pbSecret []byte, pbInput []byte, pbOutput []byte) (ntstatus error) = bcrypt.BCryptHash
//sys	GenRandom(hAlgorithm BCRYPT_ALG_HANDLE, pbBuffer []byte, dwFlags BCRYPTGENRANDOM_FLAGS) (ntstatus error) = bcrypt.BCryptGenRandom
//sys	Encapsulate(hKey BCRYPT_KEY_HANDLE, pbSecretKey []byte, pcbSecretKey *uint32, pbCipherText []byte, pcbCipherText *uint32, dwFlags uint32) (ntstatus error) = bcrypt.BCryptEncapsulate
//sys	Decapsulate(hKey BCRYPT_KEY_HANDLE, pbCipherText []byte, pbSecretKey []byte, pcbSecretKey *uint32, dwFlags uint32) (ntstatus error) = bcrypt.BCryptDecapsulate
//sys	GetFipsAlgorithmMode(pfEnabled *uint8) (ntstatus error) = bcrypt.BCryptGetFipsAlgorithmMode

// Types used in generated APIs for

type BCRYPT_FLAGS uint32

const (
	BCRYPT_BLOCK_PADDING BCRYPT_FLAGS = 0x1
	BCRYPT_PAD_NONE      BCRYPT_FLAGS = 0x1
	BCRYPT_PAD_OAEP      BCRYPT_FLAGS = 0x4
	BCRYPT_PAD_PKCS1     BCRYPT_FLAGS = 0x2
	BCRYPT_PAD_PSS       BCRYPT_FLAGS = 0x8
)

type BCRYPT_OPEN_ALGORITHM_PROVIDER_FLAGS uint32

const (
	BCRYPT_ALG_HANDLE_HMAC_FLAG BCRYPT_OPEN_ALGORITHM_PROVIDER_FLAGS = 0x8
	BCRYPT_PROV_DISPATCH        BCRYPT_OPEN_ALGORITHM_PROVIDER_FLAGS = 0x1
	BCRYPT_HASH_REUSABLE_FLAG   BCRYPT_OPEN_ALGORITHM_PROVIDER_FLAGS = 0x20
)

type BCRYPT_DSA_MAGIC uint32

const (
	BCRYPT_DSA_PUBLIC_MAGIC  BCRYPT_DSA_MAGIC = 0x42505344
	BCRYPT_DSA_PRIVATE_MAGIC BCRYPT_DSA_MAGIC = 0x56505344
)

type BCRYPT_RSAKEY_BLOB_MAGIC uint32

const (
	BCRYPT_RSAPUBLIC_MAGIC      BCRYPT_RSAKEY_BLOB_MAGIC = 0x31415352
	BCRYPT_RSAPRIVATE_MAGIC     BCRYPT_RSAKEY_BLOB_MAGIC = 0x32415352
	BCRYPT_RSAFULLPRIVATE_MAGIC BCRYPT_RSAKEY_BLOB_MAGIC = 0x33415352
)

type BCRYPTGENRANDOM_FLAGS uint32

const (
	BCRYPT_RNG_USE_ENTROPY_IN_BUFFER BCRYPTGENRANDOM_FLAGS = 0x1
	BCRYPT_USE_SYSTEM_PREFERRED_RNG  BCRYPTGENRANDOM_FLAGS = 0x2
)

type BCRYPT_ALG_HANDLE unsafe.Pointer

type BCRYPT_KEY_HANDLE unsafe.Pointer

type BCRYPT_HASH_HANDLE unsafe.Pointer

type BCRYPT_SECRET_HANDLE unsafe.Pointer

type BCRYPT_HANDLE unsafe.Pointer

type KEY_LENGTHS_STRUCT struct {
	DwMinLength uint32
	DwMaxLength uint32
	DwIncrement uint32
}

type BCryptBufferDesc struct {
	UlVersion uint32
	CBuffers  uint32
	PBuffers  *BCryptBuffer
}

type RSAKEY_BLOB struct {
	Magic       BCRYPT_RSAKEY_BLOB_MAGIC
	BitLength   uint32
	CbPublicExp uint32
	CbModulus   uint32
	CbPrime1    uint32
	CbPrime2    uint32
}

type ECCKEY_BLOB struct {
	DwMagic uint32
	CbKey   uint32
}

type DSA_KEY_BLOB struct {
	DwMagic BCRYPT_DSA_MAGIC
	CbKey   uint32
	Count   [4]uint8
	Seed    [20]uint8
	Q       [20]uint8
}

type HASHALGORITHM_ENUM int32

const (
	DSA_HASH_ALGORITHM_SHA1   HASHALGORITHM_ENUM = 0x0
	DSA_HASH_ALGORITHM_SHA256 HASHALGORITHM_ENUM = 0x1
	DSA_HASH_ALGORITHM_SHA512 HASHALGORITHM_ENUM = 0x2
)

type DSAFIPSVERSION_ENUM int32

const (
	DSA_FIPS186_2 DSAFIPSVERSION_ENUM = 0x0
	DSA_FIPS186_3 DSAFIPSVERSION_ENUM = 0x1
)

type DSA_KEY_BLOB_V2 struct {
	DwMagic         BCRYPT_DSA_MAGIC
	CbKey           uint32
	HashAlgorithm   HASHALGORITHM_ENUM
	StandardVersion DSAFIPSVERSION_ENUM
	CbSeedLength    uint32
	CbGroupSize     uint32
	Count           [4]uint8
}

type KEY_DATA_BLOB_HEADER struct {
	DwMagic   uint32
	DwVersion uint32
	CbKeyData uint32
}

type MLKEM_KEY_BLOB struct {
	DwMagic        uint32
	CbParameterSet uint32
	CbKey          uint32
}

type DSA_PARAMETER_HEADER struct {
	CbLength    uint32
	DwMagic     uint32
	CbKeyLength uint32
	Count       [4]uint8
	Seed        [20]uint8
	Q           [20]uint8
}

type DSA_PARAMETER_HEADER_V2 struct {
	CbLength        uint32
	DwMagic         uint32
	CbKeyLength     uint32
	HashAlgorithm   HASHALGORITHM_ENUM
	StandardVersion DSAFIPSVERSION_ENUM
	CbSeedLength    uint32
	CbGroupSize     uint32
	Count           [4]uint8
}

type BCryptBuffer struct {
	CbBuffer   uint32
	BufferType uint32
	PvBuffer   unsafe.Pointer
}
