// Code generated by gowinmd; DO NOT EDIT.

package bcrypt

import "unsafe"

var _ unsafe.Pointer

// APIs for Windows.Win32.Security.Cryptography
//sys	RawOpenAlgorithmProvider(phAlgorithm *BCRYPT_ALG_HANDLE, pszAlgId *PWSTRElement, pszImplementation *PWSTRElement, dwFlags BCRYPT_OPEN_ALGORITHM_PROVIDER_FLAGS) (r NTSTATUS) = bcrypt.dll.BCryptOpenAlgorithmProvider
//sys	RawGetProperty(hObject BCRYPT_HANDLE, pszProperty *PWSTRElement, pbOutput *uint8, cbOutput uint32, pcbResult *uint32, dwFlags uint32) (r NTSTATUS) = bcrypt.dll.BCryptGetProperty
//sys	RawSetProperty(hObject BCRYPT_HANDLE, pszProperty *PWSTRElement, pbInput *uint8, cbInput uint32, dwFlags uint32) (r NTSTATUS) = bcrypt.dll.BCryptSetProperty
//sys	RawCloseAlgorithmProvider(hAlgorithm BCRYPT_ALG_HANDLE, dwFlags uint32) (r NTSTATUS) = bcrypt.dll.BCryptCloseAlgorithmProvider
//sys	RawGenerateSymmetricKey(hAlgorithm BCRYPT_ALG_HANDLE, phKey *BCRYPT_KEY_HANDLE, pbKeyObject *uint8, cbKeyObject uint32, pbSecret *uint8, cbSecret uint32, dwFlags uint32) (r NTSTATUS) = bcrypt.dll.BCryptGenerateSymmetricKey
//sys	RawGenerateKeyPair(hAlgorithm BCRYPT_ALG_HANDLE, phKey *BCRYPT_KEY_HANDLE, dwLength uint32, dwFlags uint32) (r NTSTATUS) = bcrypt.dll.BCryptGenerateKeyPair
//sys	RawEncrypt(hKey BCRYPT_KEY_HANDLE, pbInput *uint8, cbInput uint32, pPaddingInfo unsafe.Pointer, pbIV *uint8, cbIV uint32, pbOutput *uint8, cbOutput uint32, pcbResult *uint32, dwFlags BCRYPT_FLAGS) (r NTSTATUS) = bcrypt.dll.BCryptEncrypt
//sys	RawDecrypt(hKey BCRYPT_KEY_HANDLE, pbInput *uint8, cbInput uint32, pPaddingInfo unsafe.Pointer, pbIV *uint8, cbIV uint32, pbOutput *uint8, cbOutput uint32, pcbResult *uint32, dwFlags BCRYPT_FLAGS) (r NTSTATUS) = bcrypt.dll.BCryptDecrypt
//sys	RawExportKey(hKey BCRYPT_KEY_HANDLE, hExportKey BCRYPT_KEY_HANDLE, pszBlobType *PWSTRElement, pbOutput *uint8, cbOutput uint32, pcbResult *uint32, dwFlags uint32) (r NTSTATUS) = bcrypt.dll.BCryptExportKey
//sys	RawImportKeyPair(hAlgorithm BCRYPT_ALG_HANDLE, hImportKey BCRYPT_KEY_HANDLE, pszBlobType *PWSTRElement, phKey *BCRYPT_KEY_HANDLE, pbInput *uint8, cbInput uint32, dwFlags uint32) (r NTSTATUS) = bcrypt.dll.BCryptImportKeyPair
//sys	RawFinalizeKeyPair(hKey BCRYPT_KEY_HANDLE, dwFlags uint32) (r NTSTATUS) = bcrypt.dll.BCryptFinalizeKeyPair
//sys	RawDestroyKey(hKey BCRYPT_KEY_HANDLE) (r NTSTATUS) = bcrypt.dll.BCryptDestroyKey
//sys	RawDestroySecret(hSecret BCRYPT_SECRET_HANDLE) (r NTSTATUS) = bcrypt.dll.BCryptDestroySecret
//sys	RawSignHash(hKey BCRYPT_KEY_HANDLE, pPaddingInfo unsafe.Pointer, pbInput *uint8, cbInput uint32, pbOutput *uint8, cbOutput uint32, pcbResult *uint32, dwFlags BCRYPT_FLAGS) (r NTSTATUS) = bcrypt.dll.BCryptSignHash
//sys	RawVerifySignature(hKey BCRYPT_KEY_HANDLE, pPaddingInfo unsafe.Pointer, pbHash *uint8, cbHash uint32, pbSignature *uint8, cbSignature uint32, dwFlags BCRYPT_FLAGS) (r NTSTATUS) = bcrypt.dll.BCryptVerifySignature
//sys	RawSecretAgreement(hPrivKey BCRYPT_KEY_HANDLE, hPubKey BCRYPT_KEY_HANDLE, phAgreedSecret *BCRYPT_SECRET_HANDLE, dwFlags uint32) (r NTSTATUS) = bcrypt.dll.BCryptSecretAgreement
//sys	RawDeriveKey(hSharedSecret BCRYPT_SECRET_HANDLE, pwszKDF *PWSTRElement, pParameterList *BCryptBufferDesc, pbDerivedKey *uint8, cbDerivedKey uint32, pcbResult *uint32, dwFlags uint32) (r NTSTATUS) = bcrypt.dll.BCryptDeriveKey
//sys	RawKeyDerivation(hKey BCRYPT_KEY_HANDLE, pParameterList *BCryptBufferDesc, pbDerivedKey *uint8, cbDerivedKey uint32, pcbResult *uint32, dwFlags uint32) (r NTSTATUS) = bcrypt.dll.BCryptKeyDerivation
//sys	RawCreateHash(hAlgorithm BCRYPT_ALG_HANDLE, phHash *BCRYPT_HASH_HANDLE, pbHashObject *uint8, cbHashObject uint32, pbSecret *uint8, cbSecret uint32, dwFlags uint32) (r NTSTATUS) = bcrypt.dll.BCryptCreateHash
//sys	RawHashData(hHash BCRYPT_HASH_HANDLE, pbInput *uint8, cbInput uint32, dwFlags uint32) (r NTSTATUS) = bcrypt.dll.BCryptHashData
//sys	RawFinishHash(hHash BCRYPT_HASH_HANDLE, pbOutput *uint8, cbOutput uint32, dwFlags uint32) (r NTSTATUS) = bcrypt.dll.BCryptFinishHash
//sys	RawDuplicateHash(hHash BCRYPT_HASH_HANDLE, phNewHash *BCRYPT_HASH_HANDLE, pbHashObject *uint8, cbHashObject uint32, dwFlags uint32) (r NTSTATUS) = bcrypt.dll.BCryptDuplicateHash
//sys	RawDestroyHash(hHash BCRYPT_HASH_HANDLE) (r NTSTATUS) = bcrypt.dll.BCryptDestroyHash
//sys	RawHash(hAlgorithm BCRYPT_ALG_HANDLE, pbSecret *uint8, cbSecret uint32, pbInput *uint8, cbInput uint32, pbOutput *uint8, cbOutput uint32) (r NTSTATUS) = bcrypt.dll.BCryptHash
//sys	RawGenRandom(hAlgorithm BCRYPT_ALG_HANDLE, pbBuffer *uint8, cbBuffer uint32, dwFlags BCRYPTGENRANDOM_FLAGS) (r NTSTATUS) = bcrypt.dll.BCryptGenRandom
//sys	RawEncapsulate(hKey BCRYPT_KEY_HANDLE, pbSecretKey *uint8, cbSecretKey uint32, pcbSecretKey *uint32, pbCipherText *uint8, cbCipherText uint32, pcbCipherText *uint32, dwFlags uint32) (r NTSTATUS) = bcrypt.dll.BCryptEncapsulate
//sys	RawDecapsulate(hKey BCRYPT_KEY_HANDLE, pbCipherText *uint8, cbCipherText uint32, pbSecretKey *uint8, cbSecretKey uint32, pcbSecretKey *uint32, dwFlags uint32) (r NTSTATUS) = bcrypt.dll.BCryptDecapsulate
//sys	RawGetFipsAlgorithmMode(pfEnabled *uint8) (r NTSTATUS) = bcrypt.dll.BCryptGetFipsAlgorithmMode

// Types used in generated APIs for

type BCRYPT_FLAGS uint32

const (
	BCRYPT_BLOCK_PADDING BCRYPT_FLAGS = 0x1
	BCRYPT_PAD_NONE      BCRYPT_FLAGS = 0x1
	BCRYPT_PAD_OAEP      BCRYPT_FLAGS = 0x4
	BCRYPT_PAD_PKCS1     BCRYPT_FLAGS = 0x2
	BCRYPT_PAD_PSS       BCRYPT_FLAGS = 0x8
)

type BCRYPT_OPEN_ALGORITHM_PROVIDER_FLAGS uint32

const (
	BCRYPT_ALG_HANDLE_HMAC_FLAG BCRYPT_OPEN_ALGORITHM_PROVIDER_FLAGS = 0x8
	BCRYPT_PROV_DISPATCH        BCRYPT_OPEN_ALGORITHM_PROVIDER_FLAGS = 0x1
	BCRYPT_HASH_REUSABLE_FLAG   BCRYPT_OPEN_ALGORITHM_PROVIDER_FLAGS = 0x20
)

type BCRYPTGENRANDOM_FLAGS uint32

const (
	BCRYPT_RNG_USE_ENTROPY_IN_BUFFER BCRYPTGENRANDOM_FLAGS = 0x1
	BCRYPT_USE_SYSTEM_PREFERRED_RNG  BCRYPTGENRANDOM_FLAGS = 0x2
)

type BCRYPT_ALG_HANDLE unsafe.Pointer

type BCRYPT_KEY_HANDLE unsafe.Pointer

type BCRYPT_HASH_HANDLE unsafe.Pointer

type BCRYPT_SECRET_HANDLE unsafe.Pointer

type NTSTATUS int32

type PWSTRElement uint16

type BCRYPT_HANDLE unsafe.Pointer

type BCryptBufferDesc struct {
	UlVersion uint32
	CBuffers  uint32
	PBuffers  *BCryptBuffer
}

type BCryptBuffer struct {
	CbBuffer   uint32
	BufferType uint32
	PvBuffer   unsafe.Pointer
}
