on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

name: Check Vendored Imports
permissions:
   contents: read
jobs:
  check-imports:
    # Verify that packages vendored into Go's standard library only use
    # allowed stdlib imports. New imports require a matching update to the
    # deps_test.go patch in microsoft-go.
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version-file: go.mod
          go-download-base-url: "https://aka.ms/golang/release/latest"

      - name: Check vendored package imports
        shell: bash
        run: |
          go run github.com/microsoft/go-infra/cmd/check-imports@v0.0.13 \
            -pkg ./internal/bcrypt \
            -allow strconv,syscall,unicode/utf16,unsafe \
            -pkg ./internal/sysdll \
            -allow syscall,unsafe \
            -pkg ./internal/subtle \
            -allow unsafe \
            -pkg ./cng/bbig \
            -allow math/big \
            -pkg ./cng
